[package]
name = "crbn-san"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
jiff = "0.2.17"
poise = "0.6.1"
serenity = "0.12.5"
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
